### ISSUE TITLE
PlatiQR в CБП

### ISSUE THREAD

**Issue by romanesko** [Doncode/sber-qr#2]
А нет ли через api способа трансформировать ссылку PlatiQR в платёж СБП (или хотя бы получить реквизиты платежа, для формирования ссылки вручную)?

Приложение Тинькофф как-то умеет из ссылки вида
https://platiqr.ru/?uuid=3002006816&amount=4800.35&trxid=2023050521303141211
получить СБПшный платёж.

Не могу найти нигде информации по теме. Вы не знаете?

**Comment by Doncode** [comment]
Возможности трансформировать ссылку мне не известно.
Через API можно получать ссылку для platiqr и для СБП.
Но когда ссылка уже создана, то трансформировать ее нельзя

**Comment by romanesko** [comment]
Жаль.
Спасибо за ответ
